var pieces = [];
var piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x00af00;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.fill_color = 0x0000af;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 0, z: 2 });
piece.fill_color = 0xaf0000;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0xafaf00;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 2 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x00afaf;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.fill_color = 0xaf00af;
piece.edge_color = 0x227f22;
pieces.push(piece);

piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.blocks.push({ x: 0, y: 2, z: 2 });
piece.fill_color = 0xfae957;
piece.edge_color = 0x227f22;
pieces.push(piece);

piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0xafafaf;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 1, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0xffb5b5;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 1, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x24240e;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 1, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x00f500;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 1, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x00f5f5;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0xf500f5;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 1, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.fill_color = 0x5f5f00;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 1, y: 2, z: 0 });
piece.blocks.push({ x: 0, y: 2, z: 0 });
piece.fill_color = 0x005f5f;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 1, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 2, y: 0, z: 0 });
piece.blocks.push({ x: 2, y: 1, z: 0 });
piece.fill_color = 0x5f005f;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 1, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 2, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.fill_color = 0x5faf00;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 2, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.fill_color = 0x00af5f;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.fill_color = 0xaf5f00;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 2, z: 1 });
piece.blocks.push({ x: 1, y: 2, z: 1 });
piece.fill_color = 0x5f5f5f;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 1, y: 1, z: 2 });
piece.fill_color = 0xffe3cf;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 2 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.fill_color = 0xd9d9d9;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 2, z: 1 });
piece.fill_color = 0xff9800;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 0 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 0, z: 1 });
piece.fill_color = 0xa3b53f;
piece.edge_color = 0x227f22;
pieces.push(piece);
piece = { blocks: [] };
piece.blocks.push({ x: 0, y: 0, z: 0 });
piece.blocks.push({ x: 0, y: 0, z: 1 });
piece.blocks.push({ x: 0, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 1 });
piece.blocks.push({ x: 1, y: 1, z: 2 });
piece.fill_color = 0x3c3fb5;
piece.edge_color = 0x227f22;
pieces.push(piece);





module.exports = {
    pieces: pieces
};